/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /dummyLogin
// Получение тестового токена 
func (api *DefaultAPI) DummyLoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /login
// Авторизация пользователя 
func (api *DefaultAPI) LoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /products
// Добавление товара в текущую приемку (только для сотрудников ПВЗ) 
func (api *DefaultAPI) ProductsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /pvz
// Получение списка ПВЗ с фильтрацией по дате приемки и пагинацией 
func (api *DefaultAPI) PvzGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /pvz
// Создание ПВЗ (только для модераторов) 
func (api *DefaultAPI) PvzPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /pvz/:pvzId/close_last_reception
// Закрытие последней открытой приемки товаров в рамках ПВЗ 
func (api *DefaultAPI) PvzPvzIdCloseLastReceptionPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /pvz/:pvzId/delete_last_product
// Удаление последнего добавленного товара из текущей приемки (LIFO, только для сотрудников ПВЗ) 
func (api *DefaultAPI) PvzPvzIdDeleteLastProductPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /receptions
// Создание новой приемки товаров (только для сотрудников ПВЗ) 
func (api *DefaultAPI) ReceptionsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /register
// Регистрация пользователя 
func (api *DefaultAPI) RegisterPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

