/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Pvz struct {

	Id string `json:"id,omitempty"`

	RegistrationDate time.Time `json:"registrationDate,omitempty"`

	City string `json:"city"`
}
