/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Product struct {

	Id string `json:"id,omitempty"`

	DateTime time.Time `json:"dateTime,omitempty"`

	Type string `json:"type"`

	ReceptionId string `json:"receptionId"`
}
