/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PvzGet200ResponseInner struct {

	Pvz Pvz `json:"pvz,omitempty"`

	Receptions []PvzGet200ResponseInnerReceptionsInner `json:"receptions,omitempty"`
}
